name: Push to Another Remote

on:
  push:
    branches:
      - main  # Trigger only when the main branch is updated

jobs:
  push_to_another_remote:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the current repository
    - name: Checkout the current repository
      uses: actions/checkout@v3

    # Step 2: Set up Git to push to the second remote
    - name: Set up Git for second remote
      run: |
        git config --global user.email "kainy.chike-onyechi@fumiwo.io"
        git config --global user.name "Kainy"
        git remote add second_remote https://github.com/kainy-fmw/fumiwo-business.git
        git fetch second_remote

    # Step 3: Push to the other remote branch
    - name: Push to the second remote branch
      run: |
        git push -f second_remote main
      env:
        # Secrets to authenticate with the second remote (GitHub or other service)
        GITHUB_TOKEN: ${{ secrets.REMOTE_TOKEN }}  # or replace with a token from the second remote
